### PR TITLE
TWRP Decryption with CM13

### PR DESCRIPTION
**Pull request by jfeise**
Fixed decryption in TWRP when used with the OP2 CM13 nightlies.

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Could anyone test & merge it if it works good? It's really awful to have missing encryption support

**Comment by bigbiff** [comment]
If you want us to merge it, you need to push it to the project at https://gerrit.twrp.me

We don't do pull requests at this time.

**Comment by ihor-sviziev** [comment]
@jfeise could you create request on gerrit?

**Comment by jfeise** [comment]
Gerrit change request: https://gerrit.twrp.me/#/c/1635/

**Comment by ihor-sviziev** [comment]
@bigbiff you've merged these changes. Could you create new build, that will include them? Thank you!

@jfeise I think you could close this PR because your changes already merged.

**Comment by bigbiff** [comment]
Hi can you guys test http://build.twrp.me/twrp/twrp-3.0.2-enc-oneplus2.img

If it works for youiI can run thepproduction build.

**Comment by bigbiff** [comment]
Hi can you guys test http://build.twrp.me/twrp/twrp-3.0.2-enc-oneplus2.img

If it works for youiI can run thepproduction build.

**Comment by bigbiff** [comment]
Hi can you guys test http://build.twrp.me/twrp/twrp-3.0.2-enc-oneplus2.img

If it works for youiI can run thepproduction build.

**Comment by jfeise** [comment]
Works for me with password:

```
Using scrypt with keymaster for cryptfs KDF
keymaster module name is Keymaster QTI HAL                                               
keymaster version is 256                                                                 
Found keymaster1 module, using keymaster1 API.                                           
Signing safely-padded object                                                                 
get_dm_crypt_version flag: 1, name: 'req-crypt'                                                    
load_crypto_mapping_table: target_type = crypt                                             
load_crypto_mapping_table: real_blk_name = /dev/block/mmcblk0p43, extra_params =
Password matches                                                                                
Data successfully decrypted, new block device: '/dev/block/dm-0'
```

**Pull request closed without merging**
